groups:
  - name: rule_1
    rules:
      - record: node_memoryfree_percent
        expr: (100 * node_memory_MemFree_bytes ) / node_memory_MemTotal_bytes

  - name: rule_2
    rules:

  #Alert for any instance that is unreachable for >5 minutes.
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
