server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.2.51:3100/loki/api/v1/push 

scrape_configs:
  - job_name: "spring_boot_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "spring_boot_logs"
          host: "client_linux"
          app: "spring-boot-app"
          __path__: /app/logs/*.log  # Le chemin où sont stockés les logs de ton application Spring Boot

